### ISSUE TITLE
[HÍBRIDO 4X Av. Faria Lima/SP] FULLSTACK Developer Node.JS/VUEJS @DQRTech

### ISSUE THREAD

**Issue by gsabreudev** [nodejsdevbr/vagas#27]
## Pessoa Desenvolvedora Fullstack NodeJS/VueJS
Categoria:

Detalhes da vaga
Publicada em
22 de novembro de 2023

 Híbrido na Faria Lima, presencial mínimo 4x.
 Efetivo
## Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## DE ONDE VOCÊ VAI TRABALHAR?
Híbrido na Faria Lima, presencial mínimo 4x.

## O QUE NOS MOVE:
Pessoas & Tecnologia! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente de setor financeiro.

## O QUE ESPERAMOS QUE VOCÊ SAIBA:
Experiência em projetos de desenvolvimento de software utilizando NodeJS e VueJS;

Banco de dados MongoDB;

Serviços de mensageria (RabbitMQ/Kafka ou semelhante);

Design Patterns GoF;

Desenvolvimento de aplicações em nuvem AWS (Lambda, SQS; SNS, DynamoDb, S3, EC2, RDS);

## O QUE SERIA LEGAL SE VOCÊ TIVESSE:
Execução de testes unitários;

Metodologia ágil;

Atuação com o mercado financeiro;

Experiência em modelagem de dados em DDD;

Conhecimento em Arquitetura de Microsserviços;

Experiencia com liderança técnica.

## QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER:
Saber atuar com autonomia, habilidades de comunicação, boa didática, iniciativa, liderança.

## O QUE OFERECEMOS PARA VOCÊ?
Auxílio alimentação no cartão Caju;

Assistência médica e odontológica da Porto Seguro e Mediservice, gratuita para você (sem coparticipação ou mensalidade);

Você ainda pode incluir seus dependentes legais com apenas 50% de desconto da mensalidade em folha;

Oferecemos auxílio Psicológico através da PsicologiaViva, estendida para dependentes;

Auxílio creche (segundo as condições vigentes da convenção coletiva do Sindpd-SP);

Seguro de vida da Porto Seguro, em grupo;

Aqui a sua indicação vale premiação de 1K;

No mês do seu aniversário tem presente;

A cada aniversário de DQR Tech, você recebe um mimo;

Notebook para o desempenho das atividades + kit de onboarding da DQR Tech;

Contrato CLT.

Todas nossas vagas são destinadas a Pluralidade e Diversidade

## VALORES DE ATÉ 15K CLT

**Edit**

Link para a vaga: https://www.dqrtech.com.br/vagas/pessoa-desenvolvedora-webfullstack-nodejs-vuejs/
(Se estiver incorreto, substituir pelo correto)

**Comment by emersonSantos98** [comment]
Olá tenho interesse!

**Comment by devCaiquedePaula** [comment]
Olá, possuo interesse na vaga

**Comment by Pauloo2003** [comment]
Ola como posso me candidatar

**Comment by lluccas** [comment]
olá tenho muito interesse

**Comment by omarcus-vinnicius** [comment]
Ola como posso me candidatar, tenho muito interesse.

**Comment by lluccas** [comment]
não entendi ?

Em ter., 2 de abr. de 2024 às 13:22, marcus vinnicius <
***@***.***> escreveu:

**Comment by guibranco** [comment]
@gsabreudev por favor, quando publicar a vaga, verificar a existência de um link ou enderçeo de e-mail para contato =D 

Para quem procura o link: https://www.dqrtech.com.br/vagas/pessoa-desenvolvedora-webfullstack-nodejs-vuejs/
